import { build } from "esbuild";
await build({
  entryPoints: ["src/index.ts"],
  outfile: "runtime/server.mjs",         // .mjs so ESM-ness never depends on a package.json shipping in the cache
  bundle: true, platform: "node", format: "esm", target: "node22",
  // REQUIRED: esbuild ESM output of CJS deps (the MCP SDK, ajv) will "Dynamic require of 'node:*' is not
  // supported" at runtime without this shim. Do not omit it.
  banner: { js: [
    "// GENERATED by esbuild — do not edit. Source: src/. Build: npm run build",
    "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);",
  ].join("\n") },
});
console.error("built runtime/server.mjs");
