// GENERATED by esbuild — do not edit. Source: src/. Build: npm run build
import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);

// src/util/logger.ts
function emit(level, msg, meta) {
  const line = JSON.stringify({ t: level, msg, ...meta ?? {} });
  process.stderr.write(line + "\n");
}
var logger = {
  debug: (m, meta) => emit("debug", m, meta),
  info: (m, meta) => emit("info", m, meta),
  warn: (m, meta) => emit("warn", m, meta),
  error: (m, meta) => emit("error", m, meta)
};

// src/index.ts
function main() {
  logger.info("claude-architect runtime placeholder");
}
export {
  main
};
